"""add bank account flip_direction

Revision ID: 08a7fcddf2df
Revises: cba5d1fe8167
Create Date: 2026-10-09 18:19:01.686283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08a7fcddf2df'
down_revision: Union[str, Sequence[str], None] = 'cba5d1fe8167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing accounts get False: until now every bank was taken at its word.
    op.add_column(
        'bankaccount',
        sa.Column('flip_direction', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('bankaccount', 'flip_direction', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('bankaccount', 'flip_direction')
