"""create the income schema

Revision ID: 10088e48f6a1
Revises: b41f7c2ad9e6
Create Date: 2026-09-05 20:01:26.367920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10088e48f6a1'
down_revision: Union[str, Sequence[str], None] = 'b41f7c2ad9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomevault',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('kdf', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kdf_salt', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kdf_memory_kib', sa.Integer(), nullable=False),
    sa.Column('kdf_iterations', sa.Integer(), nullable=False),
    sa.Column('kdf_parallelism', sa.Integer(), nullable=False),
    sa.Column('wrapped_dek', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('incomeclient',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_ct', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('note_ct', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('default_rate_minor', sa.BigInteger(), nullable=False),
    sa.Column('default_account_id', sa.Uuid(), nullable=False),
    sa.Column('default_category_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('default_rate_minor >= 0', name='ck_incomeclient_rate_non_negative'),
    sa.ForeignKeyConstraint(['default_account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_incomeclient_account_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['default_category_id', 'household_id'], ['category.id', 'category.household_id'], name='fk_incomeclient_category_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'household_id', name='uq_incomeclient_id_household')
    )
    op.create_index(op.f('ix_incomeclient_household_id'), 'incomeclient', ['household_id'], unique=False)
    op.create_index(op.f('ix_incomeclient_owner_user_id'), 'incomeclient', ['owner_user_id'], unique=False)
    op.create_table('incomesession',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ATTENDED', 'MISSED', 'CANCELLED', name='incomesessionstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'WAIVED', name='paymentstatus'), nullable=False),
    sa.Column('occurs_on', sa.Date(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('note_ct', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(payment_status = 'PAID' AND paid_on IS NOT NULL) OR (payment_status <> 'PAID' AND paid_on IS NULL)", name='ck_incomesession_paid_on_shape'),
    sa.CheckConstraint('fee_minor >= 0', name='ck_incomesession_fee_non_negative'),
    sa.ForeignKeyConstraint(['client_id', 'household_id'], ['incomeclient.id', 'incomeclient.household_id'], name='fk_incomesession_client_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incomesession_client_occurs', 'incomesession', ['client_id', 'occurs_on'], unique=False)
    op.create_index(op.f('ix_incomesession_household_id'), 'incomesession', ['household_id'], unique=False)
    op.create_index('ix_incomesession_household_occurs', 'incomesession', ['household_id', 'occurs_on'], unique=False)
    op.create_index('ix_incomesession_household_payment_occurs', 'incomesession', ['household_id', 'payment_status', 'occurs_on'], unique=False)
    op.create_index('ix_incomesession_household_status_occurs', 'incomesession', ['household_id', 'status', 'occurs_on'], unique=False)
    # Existing households predate the column, and it is NOT NULL, so the
    # default is what fills them in rather than failing the migration.
    op.add_column(
        'household',
        sa.Column(
            'session_merchant_label',
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
            server_default='Session',
        ),
    )
    op.add_column('transaction', sa.Column('income_session_id', sa.Uuid(), nullable=True))
    op.create_index('uq_transaction_income_session', 'transaction', ['income_session_id'], unique=True, postgresql_where=sa.text('income_session_id IS NOT NULL'))
    op.create_foreign_key(
        'fk_transaction_income_session',
        'transaction',
        'incomesession',
        ['income_session_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_income_session', 'transaction', type_='foreignkey')
    op.drop_index('uq_transaction_income_session', table_name='transaction', postgresql_where=sa.text('income_session_id IS NOT NULL'))
    op.drop_column('transaction', 'income_session_id')
    op.drop_column('household', 'session_merchant_label')
    op.drop_index('ix_incomesession_household_status_occurs', table_name='incomesession')
    op.drop_index('ix_incomesession_household_payment_occurs', table_name='incomesession')
    op.drop_index('ix_incomesession_household_occurs', table_name='incomesession')
    op.drop_index(op.f('ix_incomesession_household_id'), table_name='incomesession')
    op.drop_index('ix_incomesession_client_occurs', table_name='incomesession')
    op.drop_table('incomesession')
    op.drop_index(op.f('ix_incomeclient_owner_user_id'), table_name='incomeclient')
    op.drop_index(op.f('ix_incomeclient_household_id'), table_name='incomeclient')
    op.drop_table('incomeclient')
    op.drop_table('incomevault')
    # Postgres keeps an enum type after the last table using it is dropped,
    # and the next upgrade would then fail on a type that already exists.
    sa.Enum(name='paymentstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incomesessionstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
