"""mirror the numeric ceilings in check constraints

Revision ID: 2cd2b8081af4
Revises: 8fe178da1853
Create Date: 2026-09-09 13:29:02.901221

The ceilings were added to the input models only, so they held for what
arrived through the API and for nothing else. These constraints are the SQL
half, next to the floors that were already there: ck_transaction_amount_positive,
ck_budget_limit_non_negative, ck_recurringrule_amount_positive,
ck_recurringrule_interval_positive, ck_trade_quantity_positive and their
siblings.

The numbers are MAX_AMOUNT_MINOR (2**62), MAX_QUANTITY_MICRO, MAX_PRICE_MICRO,
MAX_FX_RATE_MICRO, MAX_RECURRENCE_INTERVAL and MAX_SORT_ORDER, rendered here as
literals because a revision is a record of what was applied and must not change
meaning when a constant does. The models build the same expressions from those
constants, and tests/unit/models/test_numeric_ceilings.py holds the two
together.

Each ADD CONSTRAINT below takes an ACCESS EXCLUSIVE lock on its table and holds
it for a full scan of every row, so this wants a quiet moment on a database with
a long ledger in it. Applying a check as NOT VALID and validating it separately
would avoid that, and needs a decision about how alembic's one transaction per
revision interacts with it, which is #148.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2cd2b8081af4'
down_revision: Union[str, Sequence[str], None] = '8fe178da1853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (table, constraint name, expression). Every ceiling this revision applies, in
# one place, so what upgrade adds and what downgrade drops cannot fall out of
# step with each other.
CEILINGS = [
    ('account', 'ck_account_opening_balance_within_cap', 'opening_balance_minor >= -4611686018427387904 AND opening_balance_minor <= 4611686018427387904'),
    ('budget', 'ck_budget_limit_within_cap', 'limit_minor <= 4611686018427387904'),
    ('category', 'ck_category_sort_order_range', 'sort_order >= 0 AND sort_order <= 10000'),
    ('fxrate', 'ck_fx_rate_within_cap', 'rate_micro <= 1000000000000'),
    ('incomeclient', 'ck_incomeclient_cadence_interval_within_cap', 'cadence_interval <= 1200'),
    ('incomeclient', 'ck_incomeclient_rate_within_cap', 'default_rate_minor <= 4611686018427387904'),
    ('incomesession', 'ck_incomesession_fee_within_cap', 'fee_minor <= 4611686018427387904'),
    ('instrument', 'ck_instrument_price_within_cap', 'last_price_micro IS NULL OR (last_price_micro <= 1000000000000000)'),
    ('recurringrule', 'ck_recurringrule_amount_within_cap', 'amount_minor <= 4611686018427387904'),
    ('recurringrule', 'ck_recurringrule_interval_within_cap', 'interval <= 1200'),
    ('trade', 'ck_trade_cash_within_cap', 'cash_amount_minor IS NULL OR (cash_amount_minor <= 4611686018427387904)'),
    ('trade', 'ck_trade_fee_within_cap', 'fee_minor <= 4611686018427387904'),
    ('trade', 'ck_trade_price_within_cap', 'price_micro <= 1000000000000000'),
    ('trade', 'ck_trade_quantity_within_cap', 'quantity_micro <= 1000000000000000'),
    ('transaction', 'ck_transaction_amount_within_cap', 'amount_minor <= 4611686018427387904'),
]


def upgrade() -> None:
    """Upgrade schema."""
    # Every bound was reachable through the API before it was added to the
    # models, so a stored row may sit outside one and would make the constraint
    # fail to apply. Two kinds of value are repaired here rather than left to
    # stop the migration.
    #
    # A schedule and an ordering carry no money: an ordering is a display hint
    # on a list a household edits by hand, and a pattern repeating less often
    # than a hundred years already raises on every read that materialises it.
    # Pulling both back into range is a repair rather than a loss.
    op.execute("UPDATE category SET sort_order = 0 WHERE sort_order < 0")
    op.execute("UPDATE category SET sort_order = 10000 WHERE sort_order > 10000")
    op.execute("UPDATE recurringrule SET interval = 1200 WHERE interval > 1200")
    op.execute("UPDATE incomeclient SET cadence_interval = 1200 WHERE cadence_interval > 1200")

    # A quote and an exchange rate are caches of somebody else's number, not
    # records of anything that happened here, and a value this far out is junk
    # rather than data. Discarding it costs one fetch and the next one replaces
    # it; `last_priced_at` is cleared with the price so that fetch is not
    # skipped as recent.
    op.execute("DELETE FROM fxrate WHERE rate_micro > 1000000000000")
    op.execute(
        "UPDATE instrument"
        " SET last_price_micro = NULL, last_price_at = NULL, last_priced_at = NULL"
        " WHERE last_price_micro > 1000000000000000"
    )

    # Money, quantities and prices are deliberately not touched the same way.
    # A trade or a ledger entry outside its cap is a record of something, and
    # clamping one silently is worse than a migration that stops and asks for
    # it to be looked at.
    for table, name, expression in CEILINGS:
        op.create_check_constraint(name, table, expression)


def downgrade() -> None:
    """Downgrade schema."""
    # The clamped and discarded rows are not restored: the values they held are
    # gone and were out of range in the first place.
    for table, name, _ in reversed(CEILINGS):
        op.drop_constraint(name, table, type_='check')
