"""add email outbox to household invite

Revision ID: 3ff8265835d4
Revises: 9ae013fa4088
Create Date: 2026-09-11 11:19:03.133703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ff8265835d4'
down_revision: Union[str, Sequence[str], None] = '9ae013fa4088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Named rather than left to Alembic, which would emit None and make the
# downgrade drop an unnamed constraint it cannot find.
FOREIGN_KEY = 'householdinvite_email_outbox_id_fkey'
INDEX = 'ix_householdinvite_email_outbox_id'


def upgrade() -> None:
    """Upgrade schema."""
    # Nothing to backfill: which message carried which invitation was never
    # recorded, so every invitation that predates this column reports no
    # delivery state, the same as one whose outbox row has been pruned.
    op.add_column('householdinvite', sa.Column('email_outbox_id', sa.Uuid(), nullable=True))
    # SET NULL rather than RESTRICT: the outbox is pruned on a retention
    # window, and a delivered message going out of it must not be a foreign
    # key that stops the pruner.
    op.create_foreign_key(
        FOREIGN_KEY, 'householdinvite', 'emailoutbox', ['email_outbox_id'], ['id'], ondelete='SET NULL'
    )
    # SET NULL makes every pruned outbox row a referential check against this
    # table; unindexed, each one is a sequential scan of every invitation.
    op.create_index(op.f(INDEX), 'householdinvite', ['email_outbox_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f(INDEX), table_name='householdinvite')
    op.drop_constraint(FOREIGN_KEY, 'householdinvite', type_='foreignkey')
    op.drop_column('householdinvite', 'email_outbox_id')
