"""create transaction table

Revision ID: 479a3c61fc57
Revises: 86ade2083fd5
Create Date: 2026-09-04 10:42:04.446334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '479a3c61fc57'
down_revision: Union[str, Sequence[str], None] = '86ade2083fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', name='transactionkind'), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('counter_account_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(kind = 'TRANSFER' AND counter_account_id IS NOT NULL AND category_id IS NULL) OR (kind <> 'TRANSFER' AND counter_account_id IS NULL)", name='ck_transaction_transfer_shape'),
    sa.CheckConstraint('amount_minor > 0', name='ck_transaction_amount_positive'),
    sa.CheckConstraint('counter_account_id IS NULL OR counter_account_id <> account_id', name='ck_transaction_distinct_accounts'),
    sa.ForeignKeyConstraint(['account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_transaction_account_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id', 'household_id'], ['category.id', 'category.household_id'], name='fk_transaction_category_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['counter_account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_transaction_counter_account_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_account_occurred', 'transaction', ['account_id', 'occurred_on'], unique=False)
    op.create_index('ix_transaction_counter_account_occurred', 'transaction', ['counter_account_id', 'occurred_on'], unique=False, postgresql_where=sa.text('counter_account_id IS NOT NULL'))
    op.create_index('ix_transaction_household_category_occurred', 'transaction', ['household_id', 'category_id', 'occurred_on'], unique=False, postgresql_where=sa.text('category_id IS NOT NULL'))
    op.create_index(op.f('ix_transaction_household_id'), 'transaction', ['household_id'], unique=False)
    op.create_index('ix_transaction_household_kind_occurred', 'transaction', ['household_id', 'kind', 'occurred_on'], unique=False)
    op.create_index('ix_transaction_household_occurred', 'transaction', ['household_id', 'occurred_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_household_occurred', table_name='transaction')
    op.drop_index('ix_transaction_household_kind_occurred', table_name='transaction')
    op.drop_index(op.f('ix_transaction_household_id'), table_name='transaction')
    op.drop_index('ix_transaction_household_category_occurred', table_name='transaction', postgresql_where=sa.text('category_id IS NOT NULL'))
    op.drop_index('ix_transaction_counter_account_occurred', table_name='transaction', postgresql_where=sa.text('counter_account_id IS NOT NULL'))
    op.drop_index('ix_transaction_account_occurred', table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum type behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    sa.Enum(name='transactionkind').drop(op.get_bind(), checkfirst=False)
