"""create budget table

Revision ID: 5140053843af
Revises: 479a3c61fc57
Create Date: 2026-09-04 10:55:30.309618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5140053843af'
down_revision: Union[str, Sequence[str], None] = '479a3c61fc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('limit_minor', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM period_month) = 1', name='ck_budget_period_month_first'),
    sa.CheckConstraint('limit_minor >= 0', name='ck_budget_limit_non_negative'),
    sa.ForeignKeyConstraint(['category_id', 'household_id'], ['category.id', 'category.household_id'], name='fk_budget_category_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'category_id', 'period_month', name='uq_budget_household_category_month')
    )
    op.create_index(op.f('ix_budget_household_id'), 'budget', ['household_id'], unique=False)
    op.create_index('ix_budget_household_period', 'budget', ['household_id', 'period_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_household_period', table_name='budget')
    op.drop_index(op.f('ix_budget_household_id'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###
