"""let a client be seen on several weekdays

Revision ID: 6c92cf69c30d
Revises: 89e1c0ac2c67
Create Date: 2026-09-05 20:41:16.776001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c92cf69c30d'
down_revision: Union[str, Sequence[str], None] = '89e1c0ac2c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing clients name no days, and an empty array is how that is
    # spelled: the schedule simply keeps the weekday it was pinned to,
    # which is exactly what those rows already did.
    op.add_column(
        'incomeclient',
        sa.Column(
            'cadence_weekdays',
            postgresql.ARRAY(sa.SmallInteger()),
            nullable=True,
            server_default='{}',
        ),
    )
    op.create_check_constraint('ck_incomeclient_cadence_weekdays_range', 'incomeclient', 'cadence_weekdays IS NULL OR (array_length(cadence_weekdays, 1) IS NULL OR (0 <= ALL(cadence_weekdays) AND 6 >= ALL(cadence_weekdays)))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_incomeclient_cadence_weekdays_range', 'incomeclient', type_='check')
    op.drop_column('incomeclient', 'cadence_weekdays')
    # ### end Alembic commands ###
