"""create mail rate limit table

Revision ID: 749d6ee122a6
Revises: c4d1e7f38b02
Create Date: 2026-09-11 20:29:12.892380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '749d6ee122a6'
down_revision: Union[str, Sequence[str], None] = 'c4d1e7f38b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailratelimit',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('SOURCE', 'RECIPIENT', name='mailratelimitkind'), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'subject', name='uq_mailratelimit_kind_subject')
    )
    op.create_index(op.f('ix_mailratelimit_window_start'), 'mailratelimit', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailratelimit_window_start'), table_name='mailratelimit')
    op.drop_table('mailratelimit')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum type behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    sa.Enum(name='mailratelimitkind').drop(op.get_bind(), checkfirst=False)
