"""create household and household member tables

Revision ID: 79021e6579d9
Revises: 05b3c28c578e
Create Date: 2026-09-04 10:15:33.692021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79021e6579d9'
down_revision: Union[str, Sequence[str], None] = '05b3c28c578e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('householdmember',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='householdrole'), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_householdmember_household_id'), 'householdmember', ['household_id'], unique=False)
    op.create_index(op.f('ix_householdmember_user_id'), 'householdmember', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_householdmember_user_id'), table_name='householdmember')
    op.drop_index(op.f('ix_householdmember_household_id'), table_name='householdmember')
    op.drop_table('householdmember')
    op.drop_table('household')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum type behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    sa.Enum(name='householdrole').drop(op.get_bind(), checkfirst=False)
