"""store every timestamp with its time zone

Revision ID: 7c3ae91f4d26
Revises: 2cd2b8081af4
Create Date: 2026-09-09 14:56:26.645438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c3ae91f4d26'
down_revision: Union[str, Sequence[str], None] = 'b7c1a9f3d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every timestamp in the schema. The values in them were all written as UTC —
# `datetime.now(UTC)`, the `CreatedAtMixin` default, `now()` on the server — so
# the conversion reads them back as UTC rather than in whatever zone the
# session happens to carry. Getting that wrong would shift every stored moment
# by the server's offset.
TIMESTAMP_COLUMNS = [
    ('account', 'archived_at'),
    ('account', 'created_at'),
    ('account', 'updated_at'),
    ('budget', 'created_at'),
    ('budget', 'updated_at'),
    ('category', 'archived_at'),
    ('category', 'created_at'),
    ('category', 'updated_at'),
    ('emailoutbox', 'created_at'),
    ('emailoutbox', 'next_attempt_at'),
    ('emailoutbox', 'sent_at'),
    ('emailoutbox', 'updated_at'),
    ('emailverification', 'created_at'),
    ('emailverification', 'expires_at'),
    ('emailverification', 'updated_at'),
    ('fxrate', 'as_of'),
    ('fxrate', 'created_at'),
    ('fxrate', 'updated_at'),
    ('household', 'created_at'),
    ('household', 'updated_at'),
    ('householdinvite', 'created_at'),
    ('householdinvite', 'expires_at'),
    ('householdinvite', 'updated_at'),
    ('householdmember', 'created_at'),
    ('householdmember', 'updated_at'),
    ('incomeclient', 'archived_at'),
    ('incomeclient', 'created_at'),
    ('incomeclient', 'updated_at'),
    ('incomesession', 'created_at'),
    ('incomesession', 'updated_at'),
    ('incomevault', 'created_at'),
    ('incomevault', 'updated_at'),
    ('instrument', 'created_at'),
    ('instrument', 'last_price_at'),
    ('instrument', 'last_priced_at'),
    ('instrument', 'updated_at'),
    ('passwordreset', 'created_at'),
    ('passwordreset', 'expires_at'),
    ('passwordreset', 'updated_at'),
    ('recurringrule', 'created_at'),
    ('recurringrule', 'updated_at'),
    ('trade', 'created_at'),
    ('trade', 'updated_at'),
    ('transaction', 'created_at'),
    ('transaction', 'updated_at'),
    ('user', 'created_at'),
    ('user', 'updated_at'),
]


def upgrade() -> None:
    """Upgrade schema."""
    for table_name, column_name in TIMESTAMP_COLUMNS:
        op.alter_column(
            table_name,
            column_name,
            existing_type=sa.DateTime(),
            type_=sa.DateTime(timezone=True),
            postgresql_using=f"{column_name} AT TIME ZONE 'UTC'",
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table_name, column_name in TIMESTAMP_COLUMNS:
        op.alter_column(
            table_name,
            column_name,
            existing_type=sa.DateTime(timezone=True),
            type_=sa.DateTime(),
            postgresql_using=f"{column_name} AT TIME ZONE 'UTC'",
        )
