"""create account table

Revision ID: 86ade2083fd5
Revises: d00a6250998b
Create Date: 2026-09-04 10:36:22.526046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86ade2083fd5'
down_revision: Union[str, Sequence[str], None] = 'd00a6250998b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'CURRENT', 'SAVINGS', 'CREDIT_CARD', name='accounttype'), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('opening_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_account_currency_code_len'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_account_household_name'),
    sa.UniqueConstraint('id', 'household_id', name='uq_account_id_household')
    )
    op.create_index(op.f('ix_account_household_id'), 'account', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_household_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum type behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    sa.Enum(name='accounttype').drop(op.get_bind(), checkfirst=False)
