"""add a schedule to income clients

Revision ID: 89e1c0ac2c67
Revises: 10088e48f6a1
Create Date: 2026-09-05 20:31:18.653739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '89e1c0ac2c67'
down_revision: Union[str, Sequence[str], None] = '10088e48f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate cannot see a new value on an existing enum, so it is added
    # by hand and before the column that is typed with it. Nothing in this
    # revision stores the value, which is what makes adding it inside a
    # transaction safe.
    op.execute("ALTER TYPE recurrencefrequency ADD VALUE IF NOT EXISTS 'DAILY'")

    op.add_column(
        'incomeclient',
        sa.Column(
            'cadence_frequency',
            # create_type=False: the type is already there, shared with
            # recurring rules. Letting SQLAlchemy try to create it again fails.
            postgresql.ENUM(
                'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY',
                name='recurrencefrequency',
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # Existing clients predate the column and it is NOT NULL, so the default is
    # what fills them in rather than failing the migration. Every one of them
    # has no pattern at all, and an interval of one is the harmless reading.
    op.add_column(
        'incomeclient',
        sa.Column('cadence_interval', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column('incomeclient', sa.Column('cadence_anchor_on', sa.Date(), nullable=True))
    op.create_check_constraint('ck_incomeclient_cadence_interval_positive', 'incomeclient', 'cadence_interval >= 1')
    op.create_check_constraint('ck_incomeclient_cadence_shape', 'incomeclient', '(cadence_frequency IS NULL AND cadence_anchor_on IS NULL) OR (cadence_frequency IS NOT NULL AND cadence_anchor_on IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_incomeclient_cadence_shape', 'incomeclient', type_='check')
    op.drop_constraint('ck_incomeclient_cadence_interval_positive', 'incomeclient', type_='check')
    op.drop_column('incomeclient', 'cadence_anchor_on')
    op.drop_column('incomeclient', 'cadence_interval')
    op.drop_column('incomeclient', 'cadence_frequency')
    # 'DAILY' is deliberately left on the enum type. Postgres cannot drop a
    # single value from one, and recreating the type would mean rewriting every
    # column that uses it. An unused value costs nothing.
    # ### end Alembic commands ###
