"""add invited user to household invite

Revision ID: 8fe178da1853
Revises: 6c92cf69c30d
Create Date: 2026-09-04 16:59:59.530886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fe178da1853'
down_revision: Union[str, Sequence[str], None] = '6c92cf69c30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Named rather than left to Alembic, which would emit None and make the
# downgrade drop an unnamed constraint it cannot find.
FOREIGN_KEY = 'householdinvite_invited_user_id_fkey'


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('householdinvite', sa.Column('invited_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_householdinvite_invited_user_id'), 'householdinvite', ['invited_user_id'], unique=False)
    op.create_foreign_key(FOREIGN_KEY, 'householdinvite', 'user', ['invited_user_id'], ['id'], ondelete='SET NULL')

    # Point the invitations that are still outstanding at the accounts that
    # have proved they hold the addresses they were sent to. Without this every
    # pending invitation would be left unredeemable by the guard that compares
    # this column.
    #
    # The verified row is what makes the match trustworthy, and this is the
    # same rule the code applies when an invitation is created: an address on a
    # profile is a claim anybody can make, so backfilling on an address match
    # alone would write whoever squatted an invited address before the upgrade
    # into the row as its recipient. An invitation whose address nobody has
    # proved is left unbound and attributed later, when it is verified.
    op.execute(
        """
        UPDATE householdinvite
        SET invited_user_id = "user".id
        FROM "user"
        WHERE lower(householdinvite.email) = lower("user".email)
          AND householdinvite.status = 'PENDING'
          AND EXISTS (
              SELECT 1
              FROM emailverification
              WHERE emailverification.user_id = "user".id
                AND lower(emailverification.email) = lower(householdinvite.email)
                AND emailverification.status = 'VERIFIED'
          )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(FOREIGN_KEY, 'householdinvite', type_='foreignkey')
    op.drop_index(op.f('ix_householdinvite_invited_user_id'), table_name='householdinvite')
    op.drop_column('householdinvite', 'invited_user_id')
