"""create api token table

Revision ID: 9ae013fa4088
Revises: 8fe178da1853
Create Date: 2026-09-11 08:10:34.691370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ae013fa4088'
down_revision: Union[str, Sequence[str], None] = 'd9f4c1b73a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apitoken',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scope', sa.Enum('READ', 'READ_WRITE', name='apitokenscope'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='apitokenstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('secret_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apitoken_token_id'), 'apitoken', ['token_id'], unique=True)
    op.create_index(op.f('ix_apitoken_user_id'), 'apitoken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apitoken_user_id'), table_name='apitoken')
    op.drop_index(op.f('ix_apitoken_token_id'), table_name='apitoken')
    op.drop_table('apitoken')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum types behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject. Both
    # were created by this revision.
    sa.Enum(name='apitokenstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='apitokenscope').drop(op.get_bind(), checkfirst=False)
