"""create the investments schema

Revision ID: a014b3429215
Revises: 379055fecba1
Create Date: 2026-09-05 14:46:26.353012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a014b3429215'
down_revision: Union[str, Sequence[str], None] = '379055fecba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A brokerage account holds the cash sitting with a broker. Autogenerate
    # cannot see a new value on an existing enum, so it is added by hand, and
    # before the tables that reference the type. Nothing in this revision uses
    # the value, which is what makes adding it inside a transaction safe.
    op.execute("ALTER TYPE accounttype ADD VALUE IF NOT EXISTS 'BROKERAGE'")

    op.create_table('fxrate',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('base_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('quote_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('rate_micro', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(base_code) = 3', name='ck_fx_rate_base_code_len'),
    sa.CheckConstraint('length(quote_code) = 3', name='ck_fx_rate_quote_code_len'),
    sa.CheckConstraint('rate_micro > 0', name='ck_fx_rate_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_code', 'quote_code', name='uq_fx_rate_pair')
    )
    op.create_table('instrument',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('kind', sa.Enum('ETF', 'STOCK', 'FUND', 'BOND', 'CRYPTO', 'OTHER', name='instrumentkind'), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('last_price_micro', sa.BigInteger(), nullable=True),
    sa.Column('last_price_at', sa.DateTime(), nullable=True),
    sa.Column('last_priced_at', sa.DateTime(), nullable=True),
    sa.Column('last_price_is_manual', sa.Boolean(), nullable=False),
    sa.CheckConstraint('last_price_micro IS NULL OR last_price_micro >= 0', name='ck_instrument_price_non_negative'),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_instrument_currency_code_len'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'symbol', name='uq_instrument_household_symbol'),
    sa.UniqueConstraint('id', 'household_id', name='uq_instrument_id_household')
    )
    op.create_index(op.f('ix_instrument_household_id'), 'instrument', ['household_id'], unique=False)
    op.create_table('trade',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('quantity_micro', sa.BigInteger(), nullable=False),
    sa.Column('price_micro', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('traded_on', sa.Date(), nullable=False),
    sa.Column('brokerage_account_id', sa.Uuid(), nullable=True),
    sa.Column('cash_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('(brokerage_account_id IS NULL AND cash_amount_minor IS NULL) OR (brokerage_account_id IS NOT NULL AND cash_amount_minor IS NOT NULL)', name='ck_trade_cash_side_complete'),
    sa.CheckConstraint('cash_amount_minor IS NULL OR cash_amount_minor >= 0', name='ck_trade_cash_non_negative'),
    sa.CheckConstraint('fee_minor >= 0', name='ck_trade_fee_non_negative'),
    sa.CheckConstraint('price_micro >= 0', name='ck_trade_price_non_negative'),
    sa.CheckConstraint('quantity_micro > 0', name='ck_trade_quantity_positive'),
    sa.ForeignKeyConstraint(['brokerage_account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_trade_brokerage_account_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id', 'household_id'], ['instrument.id', 'instrument.household_id'], name='fk_trade_instrument_household', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_household_id'), 'trade', ['household_id'], unique=False)
    op.create_index('ix_trade_household_traded_on', 'trade', ['household_id', 'traded_on'], unique=False)
    op.create_index('ix_trade_instrument_traded_on', 'trade', ['instrument_id', 'traded_on'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_trade_instrument_traded_on', table_name='trade')
    op.drop_index('ix_trade_household_traded_on', table_name='trade')
    op.drop_index(op.f('ix_trade_household_id'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_instrument_household_id'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_table('fxrate')

    # Alembic drops the tables but leaves the Postgres enum types behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    sa.Enum(name='tradeside').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='instrumentkind').drop(op.get_bind(), checkfirst=False)

    # The account type value is deliberately left in place. Removing one from a
    # Postgres enum means rebuilding the type and every column that uses it, and
    # a value nothing references is harmless.
