"""add category archived_with_parent

Revision ID: b41c7e5a9d02
Revises: 2cd2b8081af4
Create Date: 2026-09-05 09:12:44.108733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b41c7e5a9d02'
down_revision: Union[str, Sequence[str], None] = '2cd2b8081af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows get False: nothing recorded which archived subcategories
    # came from a cascade, so treating them as archived on their own leaves
    # them where the household last saw them rather than restoring a branch
    # that was never asked for.
    op.add_column(
        'category',
        sa.Column('archived_with_parent', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('category', 'archived_with_parent', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('category', 'archived_with_parent')
