"""add promoted_to_owner_at to household member

Revision ID: b71c5a90e3d4
Revises: e3a7b0c91f52
Create Date: 2026-09-11 21:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b71c5a90e3d4'
down_revision: Union[str, Sequence[str], None] = 'e3a7b0c91f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable, with no back fill: an owner promoted before this column existed
    # cannot be told apart from one who was made an owner deliberately, and
    # claiming either would be a guess. Null reads as "nothing to say".
    op.add_column(
        'householdmember',
        sa.Column('promoted_to_owner_at', sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('householdmember', 'promoted_to_owner_at')
