"""create email outbox table

Revision ID: b7c1a9f3d2e4
Revises: b41c7e5a9d02
Create Date: 2026-09-05 09:12:44.113920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7c1a9f3d2e4'
down_revision: Union[str, Sequence[str], None] = 'b41c7e5a9d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailoutbox',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_to', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('html_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='emailoutboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailoutbox_email_to'), 'emailoutbox', ['email_to'], unique=False)
    op.create_index(op.f('ix_emailoutbox_next_attempt_at'), 'emailoutbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_emailoutbox_status'), 'emailoutbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emailoutbox_status'), table_name='emailoutbox')
    op.drop_index(op.f('ix_emailoutbox_next_attempt_at'), table_name='emailoutbox')
    op.drop_index(op.f('ix_emailoutbox_email_to'), table_name='emailoutbox')
    op.drop_table('emailoutbox')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum type behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    sa.Enum(name='emailoutboxstatus').drop(op.get_bind(), checkfirst=False)
