"""add locale to household

Revision ID: c4d1e7f38b02
Revises: 3ff8265835d4
Create Date: 2026-09-11 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4d1e7f38b02'
down_revision: Union[str, Sequence[str], None] = '3ff8265835d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable, with no back fill: a household that has never said how it
    # writes numbers is one whose readers each follow their own browser, which
    # is what every household did before this column existed.
    op.add_column('household', sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('household', 'locale')
