"""add clients_enabled to user

Revision ID: c4e8a1f07b26
Revises: b71c5a90e3d4
Create Date: 2026-10-03 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4e8a1f07b26'
down_revision: Union[str, Sequence[str], None] = 'b71c5a90e3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Off for everyone, existing users included: the Clients screen is opt-in,
    # and nobody relies on it yet.
    op.add_column(
        'user',
        sa.Column('clients_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('user', 'clients_enabled')
