"""create recurring rule table

Revision ID: c767b0d5598b
Revises: 5140053843af
Create Date: 2026-09-04 11:15:33.278848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c767b0d5598b'
down_revision: Union[str, Sequence[str], None] = '5140053843af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurringrule',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='recurrencefrequency'), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    # transactionkind was created with the transaction table. Referencing it
    # with create_type=False stops Alembic emitting a second CREATE TYPE,
    # which would fail with DuplicateObject.
    sa.Column('kind', postgresql.ENUM(name='transactionkind', create_type=False), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('counter_account_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('next_occurrence_on', sa.Date(), nullable=True),
    sa.Column('last_generated_on', sa.Date(), nullable=True),
    sa.CheckConstraint("(kind = 'TRANSFER' AND counter_account_id IS NOT NULL AND category_id IS NULL) OR (kind <> 'TRANSFER' AND counter_account_id IS NULL)", name='ck_recurringrule_transfer_shape'),
    sa.CheckConstraint('amount_minor > 0', name='ck_recurringrule_amount_positive'),
    sa.CheckConstraint('counter_account_id IS NULL OR counter_account_id <> account_id', name='ck_recurringrule_distinct_accounts'),
    sa.CheckConstraint('day_of_month IS NULL OR (day_of_month >= 1 AND day_of_month <= 31)', name='ck_recurringrule_day_of_month_range'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_recurringrule_date_order'),
    sa.CheckConstraint('interval >= 1', name='ck_recurringrule_interval_positive'),
    sa.ForeignKeyConstraint(['account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_recurringrule_account_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id', 'household_id'], ['category.id', 'category.household_id'], name='fk_recurringrule_category_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['counter_account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_recurringrule_counter_account_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurringrule_due', 'recurringrule', ['household_id', 'next_occurrence_on'], unique=False)
    op.create_index(op.f('ix_recurringrule_household_id'), 'recurringrule', ['household_id'], unique=False)
    op.add_column('transaction', sa.Column('recurring_rule_id', sa.Uuid(), nullable=True))
    # server_default so the column can be added to a table that already has
    # rows; every existing transaction was entered by hand.
    op.add_column(
        'transaction',
        sa.Column('is_generated', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index('uq_transaction_rule_occurrence', 'transaction', ['recurring_rule_id', 'occurred_on'], unique=True, postgresql_where=sa.text('recurring_rule_id IS NOT NULL'))
    op.create_foreign_key(
        'fk_transaction_recurring_rule',
        'transaction',
        'recurringrule',
        ['recurring_rule_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_recurring_rule', 'transaction', type_='foreignkey')
    op.drop_index('uq_transaction_rule_occurrence', table_name='transaction', postgresql_where=sa.text('recurring_rule_id IS NOT NULL'))
    op.drop_column('transaction', 'is_generated')
    op.drop_column('transaction', 'recurring_rule_id')
    op.drop_index(op.f('ix_recurringrule_household_id'), table_name='recurringrule')
    op.drop_index('ix_recurringrule_due', table_name='recurringrule')
    op.drop_table('recurringrule')
    # ### end Alembic commands ###
    # Only the type this revision created. transactionkind belongs to the
    # revision that created the transaction table.
    sa.Enum(name='recurrencefrequency').drop(op.get_bind(), checkfirst=False)
