"""create bank sync tables

Revision ID: cba5d1fe8167
Revises: cfa580a8e358
Create Date: 2026-10-09 13:14:51.367896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba5d1fe8167'
down_revision: Union[str, Sequence[str], None] = 'cfa580a8e358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankconnection',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('aspsp_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('aspsp_country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'REVOKED', 'FAILED', name='bankconnectionstatus'), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('next_auto_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(aspsp_country) = 2', name='ck_bankconnection_country_len'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'household_id', name='uq_bankconnection_id_household'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('state')
    )
    op.create_index(op.f('ix_bankconnection_household_id'), 'bankconnection', ['household_id'], unique=False)
    op.create_index(op.f('ix_bankconnection_next_auto_sync_at'), 'bankconnection', ['next_auto_sync_at'], unique=False)
    op.create_table('bankaccount',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('provider_account_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('identity_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(length=34), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('import_from', sa.Date(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_booked_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_bankaccount_account_household', ondelete='SET NULL (account_id)'),
    sa.ForeignKeyConstraint(['connection_id', 'household_id'], ['bankconnection.id', 'bankconnection.household_id'], name='fk_bankaccount_connection_household', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'identity_key', name='uq_bankaccount_household_identity'),
    sa.UniqueConstraint('id', 'household_id', name='uq_bankaccount_id_household')
    )
    op.create_index(op.f('ix_bankaccount_connection_id'), 'bankaccount', ['connection_id'], unique=False)
    op.create_index(op.f('ix_bankaccount_household_id'), 'bankaccount', ['household_id'], unique=False)
    op.create_index('uq_bankaccount_account', 'bankaccount', ['account_id'], unique=True, postgresql_where=sa.text('account_id IS NOT NULL'))
    op.create_table('banksyncrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'AUTO', name='banksynctrigger'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='banksyncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['connection_id', 'household_id'], ['bankconnection.id', 'bankconnection.household_id'], name='fk_banksyncrun_connection_household', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'household_id', name='uq_banksyncrun_id_household')
    )
    op.create_index(op.f('ix_banksyncrun_connection_id'), 'banksyncrun', ['connection_id'], unique=False)
    op.create_index(op.f('ix_banksyncrun_household_id'), 'banksyncrun', ['household_id'], unique=False)
    op.create_table('banktransaction',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('sync_run_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('direction', sa.Enum('CREDIT', 'DEBIT', name='bankdirection'), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('counterparty_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('counterparty_iban', sqlmodel.sql.sqltypes.AutoString(length=34), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'ACCEPTED', 'SKIPPED', name='bankreviewstatus'), nullable=False),
    sa.Column('ledger_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_minor <= 4611686018427387904', name='ck_banktransaction_amount_within_cap'),
    sa.CheckConstraint('amount_minor > 0', name='ck_banktransaction_amount_positive'),
    sa.ForeignKeyConstraint(['bank_account_id', 'household_id'], ['bankaccount.id', 'bankaccount.household_id'], name='fk_banktransaction_bankaccount_household', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['transaction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_run_id', 'household_id'], ['banksyncrun.id', 'banksyncrun.household_id'], name='fk_banktransaction_syncrun_household', ondelete='SET NULL (sync_run_id)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'dedupe_key', name='uq_banktransaction_account_dedupe')
    )
    op.create_index(op.f('ix_banktransaction_household_id'), 'banktransaction', ['household_id'], unique=False)
    op.create_index('ix_banktransaction_household_status_occurred', 'banktransaction', ['household_id', 'review_status', 'occurred_on'], unique=False)
    op.create_index('ix_banktransaction_ledger_transaction', 'banktransaction', ['ledger_transaction_id'], unique=False, postgresql_where=sa.text('ledger_transaction_id IS NOT NULL'))
    op.create_index('uq_transaction_account_external_id', 'transaction', ['account_id', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_foreign_key('fk_transaction_import_batch_household', 'transaction', 'banksyncrun', ['import_batch_id', 'household_id'], ['id', 'household_id'], ondelete='SET NULL (import_batch_id)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_import_batch_household', 'transaction', type_='foreignkey')
    op.drop_index('uq_transaction_account_external_id', table_name='transaction', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('ix_banktransaction_ledger_transaction', table_name='banktransaction', postgresql_where=sa.text('ledger_transaction_id IS NOT NULL'))
    op.drop_index('ix_banktransaction_household_status_occurred', table_name='banktransaction')
    op.drop_index(op.f('ix_banktransaction_household_id'), table_name='banktransaction')
    op.drop_table('banktransaction')
    op.drop_index(op.f('ix_banksyncrun_household_id'), table_name='banksyncrun')
    op.drop_index(op.f('ix_banksyncrun_connection_id'), table_name='banksyncrun')
    op.drop_table('banksyncrun')
    op.drop_index('uq_bankaccount_account', table_name='bankaccount', postgresql_where=sa.text('account_id IS NOT NULL'))
    op.drop_index(op.f('ix_bankaccount_household_id'), table_name='bankaccount')
    op.drop_index(op.f('ix_bankaccount_connection_id'), table_name='bankaccount')
    op.drop_table('bankaccount')
    op.drop_index(op.f('ix_bankconnection_next_auto_sync_at'), table_name='bankconnection')
    op.drop_index(op.f('ix_bankconnection_household_id'), table_name='bankconnection')
    op.drop_table('bankconnection')
    # ### end Alembic commands ###
    # Dropping the tables leaves their enum types behind, and a later upgrade
    # would then fail to create them again.
    for name in ('bankreviewstatus', 'bankdirection', 'banksyncstatus', 'banksynctrigger', 'bankconnectionstatus'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=False)
