"""create goal table

Revision ID: cfa580a8e358
Revises: c4e8a1f07b26
Create Date: 2026-10-03 15:05:25.798116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel

from app.core.migrations import add_check_constraint, drop_check_constraint


# revision identifiers, used by Alembic.
revision: str = 'cfa580a8e358'
down_revision: Union[str, Sequence[str], None] = 'c4e8a1f07b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('target_minor', sa.BigInteger(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('target_minor <= 4611686018427387904', name='ck_goal_target_within_cap'),
    sa.CheckConstraint('target_minor > 0', name='ck_goal_target_positive'),
    sa.ForeignKeyConstraint(['account_id', 'household_id'], ['account.id', 'account.household_id'], name='fk_goal_account_household', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_goal_household_name'),
    sa.UniqueConstraint('id', 'household_id', name='uq_goal_id_household')
    )
    op.create_index(op.f('ix_goal_account_id'), 'goal', ['account_id'], unique=False)
    op.create_index(op.f('ix_goal_household_id'), 'goal', ['household_id'], unique=False)
    op.add_column('transaction', sa.Column('goal_id', sa.Uuid(), nullable=True))
    op.create_index('ix_transaction_goal_occurred', 'transaction', ['goal_id', 'occurred_on'], unique=False, postgresql_where=sa.text('goal_id IS NOT NULL'))
    op.create_foreign_key('fk_transaction_goal_household', 'transaction', 'goal', ['goal_id', 'household_id'], ['id', 'household_id'], ondelete='SET NULL (goal_id)')
    # ### end Alembic commands ###
    # Last, because the helper commits what came before it. The column is new
    # and null on every row, so the validation scan has nothing to reject.
    add_check_constraint('ck_transaction_goal_transfer_only', 'transaction', "goal_id IS NULL OR kind = 'TRANSFER'")


def downgrade() -> None:
    """Downgrade schema."""
    drop_check_constraint('ck_transaction_goal_transfer_only', 'transaction')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_goal_household', 'transaction', type_='foreignkey')
    op.drop_index('ix_transaction_goal_occurred', table_name='transaction', postgresql_where=sa.text('goal_id IS NOT NULL'))
    op.drop_column('transaction', 'goal_id')
    op.drop_index(op.f('ix_goal_household_id'), table_name='goal')
    op.drop_index(op.f('ix_goal_account_id'), table_name='goal')
    op.drop_table('goal')
    # ### end Alembic commands ###
