"""create category table

Revision ID: d00a6250998b
Revises: 79021e6579d9
Create Date: 2026-09-04 10:28:21.461462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd00a6250998b'
down_revision: Union[str, Sequence[str], None] = '79021e6579d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('kind', sa.Enum('EXPENSE', 'INCOME', name='categorykind'), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'household_id', name='uq_category_id_household')
    )
    op.create_index(op.f('ix_category_household_id'), 'category', ['household_id'], unique=False)
    op.create_index('ix_category_household_parent', 'category', ['household_id', 'parent_id'], unique=False)
    op.create_index('uq_category_household_child_name', 'category', ['household_id', 'parent_id', 'name'], unique=True, postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.create_index('uq_category_household_root_name', 'category', ['household_id', 'name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_category_household_root_name', table_name='category', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index('uq_category_household_child_name', table_name='category', postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_index('ix_category_household_parent', table_name='category')
    op.drop_index(op.f('ix_category_household_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum type behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    sa.Enum(name='categorykind').drop(op.get_bind(), checkfirst=False)
