"""back fill the category cascade mark

Revision ID: d9f4c1b73a85
Revises: 7c3ae91f4d26
Create Date: 2026-09-11 04:51:41.662965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9f4c1b73a85'
down_revision: Union[str, Sequence[str], None] = '7c3ae91f4d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Recover, for the archives that predate `category.archived_with_parent`, which
# subcategories a parent's archive took down.
#
# The cascade did not record it, but it left a fingerprint: it copied the
# parent's own `archived_at` onto every child it archived, so the two rows hold
# the identical instant down to the microsecond. Two separate requests do not
# land on the same microsecond -- each takes its own `datetime.now(UTC)` -- so
# an exact match is the cascade and nothing else. That is a much narrower claim
# than the equal-to-the-second guess #29 turned down, and narrow in the safe
# direction: a child retired on a day of its own keeps its archive, which is
# the mistake that would be visible to a household.
#
# Only rows that are still `false` are touched, so re-running this is a no-op
# and a cascade recorded since the column exists is left as it was written.
BACK_FILL_SQL = """
UPDATE category AS child
SET archived_with_parent = true
FROM category AS parent
WHERE child.parent_id = parent.id
  AND child.archived_with_parent = false
  AND child.archived_at IS NOT NULL
  AND parent.archived_at IS NOT NULL
  AND child.archived_at = parent.archived_at
"""


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(BACK_FILL_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    # Nothing to undo. The mark this sets is indistinguishable from one the
    # cascade wrote itself, so clearing it again would also clear the rows the
    # application has recorded since, and the column it writes is dropped by
    # b41c7e5a9d02 on the way further down regardless.
    pass
