"""empty the bodies the outbox has settled

Revision ID: e3a7b0c91f52
Revises: 749d6ee122a6
Create Date: 2026-09-11 09:12:03.114520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3a7b0c91f52'
down_revision: Union[str, Sequence[str], None] = '749d6ee122a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Take the rendered bodies out of the rows that were settled before the outbox
# started emptying them itself.
#
# Every reset, verification and invite the deployment has ever sent spelled a
# single-use credential out in its body, and those bodies are still sitting in
# the table -- in plaintext, and in every dump and backup taken since. The
# application no longer writes them for a settled row, but nothing would take
# away the ones already written until retention eventually removed the row.
#
# Only settled rows are touched: what is still `pending` is still owed to
# somebody, and the body is what the next attempt sends.
EMPTY_SETTLED_BODIES_SQL = """
UPDATE emailoutbox
SET html_content = ''
WHERE status IN ('SENT', 'FAILED')
  AND html_content <> ''
"""


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(EMPTY_SETTLED_BODIES_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    # Nothing to undo: the bodies are gone, and they are what this was for.
    pass
