"""create household invite table

Revision ID: f19070ecfd19
Revises: c767b0d5598b
Create Date: 2026-09-04 11:25:06.389348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types into autogenerated migrations, so the
# import has to be present whether or not this revision happens to use one.
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f19070ecfd19'
down_revision: Union[str, Sequence[str], None] = 'c767b0d5598b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('householdinvite',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    # householdrole was created with the household member table. Referencing
    # it with create_type=False stops Alembic emitting a second CREATE TYPE,
    # which would fail with DuplicateObject.
    sa.Column('role', postgresql.ENUM(name='householdrole', create_type=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='householdinvitestatus'), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_householdinvite_email'), 'householdinvite', ['email'], unique=False)
    op.create_index(op.f('ix_householdinvite_household_id'), 'householdinvite', ['household_id'], unique=False)
    op.create_index(op.f('ix_householdinvite_token'), 'householdinvite', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_householdinvite_token'), table_name='householdinvite')
    op.drop_index(op.f('ix_householdinvite_household_id'), table_name='householdinvite')
    op.drop_index(op.f('ix_householdinvite_email'), table_name='householdinvite')
    op.drop_table('householdinvite')
    # ### end Alembic commands ###
    # Alembic drops the table but leaves the Postgres enum type behind, so a
    # downgrade followed by an upgrade would fail with DuplicateObject.
    # Only the type this revision created. householdrole belongs to the
    # revision that created the household member table.
    sa.Enum(name='householdinvitestatus').drop(op.get_bind(), checkfirst=False)
