// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountCreate
 */
export type AccountCreate = {
    /**
     * Name
     */
    name: string;
    type: AccountType;
    /**
     * Institution
     */
    institution?: string | null;
    /**
     * Opening Balance Minor
     */
    opening_balance_minor?: number;
    /**
     * Opening Balance Date
     */
    opening_balance_date: string;
};

/**
 * AccountPublic
 */
export type AccountPublic = {
    /**
     * Name
     */
    name: string;
    type: AccountType;
    /**
     * Institution
     */
    institution?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Currency Code
     */
    currency_code: string;
    /**
     * Opening Balance Minor
     */
    opening_balance_minor: number;
    /**
     * Opening Balance Date
     */
    opening_balance_date: string;
    /**
     * Current Balance Minor
     */
    current_balance_minor?: number;
    /**
     * Archived At
     */
    archived_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * AccountType
 */
export const AccountType = {
    CASH: 'cash',
    CURRENT: 'current',
    SAVINGS: 'savings',
    CREDIT_CARD: 'credit_card'
} as const;

/**
 * AccountType
 */
export type AccountType = typeof AccountType[keyof typeof AccountType];

/**
 * AccountUpdate
 */
export type AccountUpdate = {
    /**
     * Name
     */
    name?: string | null;
    type?: AccountType | null;
    /**
     * Institution
     */
    institution?: string | null;
    /**
     * Is Archived
     */
    is_archived?: boolean | null;
};

/**
 * AccountsPublic
 */
export type AccountsPublic = {
    /**
     * Data
     */
    data: Array<AccountPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Total Balance Minor
     */
    total_balance_minor?: number;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BudgetBulkUpsert
 *
 * The complete set of limits for one month.
 */
export type BudgetBulkUpsert = {
    /**
     * Month
     */
    month: string;
    /**
     * Entries
     */
    entries: Array<BudgetEntry>;
};

/**
 * BudgetCopyRequest
 *
 * Copy a month of limits onto another month.
 */
export type BudgetCopyRequest = {
    /**
     * From Month
     */
    from_month: string;
    /**
     * To Month
     */
    to_month: string;
    /**
     * Overwrite
     */
    overwrite?: boolean;
};

/**
 * BudgetCreate
 */
export type BudgetCreate = {
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Month
     */
    month: string;
    /**
     * Limit Minor
     */
    limit_minor: number;
};

/**
 * BudgetEntry
 *
 * One category limit within a bulk update.
 */
export type BudgetEntry = {
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Limit Minor
     */
    limit_minor: number;
};

/**
 * BudgetProgressReport
 */
export type BudgetProgressReport = {
    period: ReportPeriod;
    /**
     * Total Limit Minor
     */
    total_limit_minor: number;
    /**
     * Total Spent Minor
     */
    total_spent_minor: number;
    /**
     * Total Remaining Minor
     */
    total_remaining_minor: number;
    /**
     * Rows
     */
    rows: Array<BudgetProgressRow>;
    /**
     * Unbudgeted Spend Minor
     */
    unbudgeted_spend_minor: number;
};

/**
 * BudgetProgressRow
 *
 * One category's spending against its limit for a month.
 */
export type BudgetProgressRow = {
    /**
     * Budget Id
     */
    budget_id: string;
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Category Name
     */
    category_name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Covers Subcategories
     */
    covers_subcategories?: boolean;
    /**
     * Limit Minor
     */
    limit_minor: number;
    /**
     * Spent Minor
     */
    spent_minor: number;
    /**
     * Remaining Minor
     */
    remaining_minor: number;
    /**
     * Progress
     */
    progress: number;
    /**
     * Is Over Budget
     */
    is_over_budget: boolean;
};

/**
 * BudgetPublic
 */
export type BudgetPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Month
     */
    month: string;
    /**
     * Limit Minor
     */
    limit_minor: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * BudgetUpdate
 */
export type BudgetUpdate = {
    /**
     * Limit Minor
     */
    limit_minor?: number | null;
};

/**
 * BudgetsPublic
 */
export type BudgetsPublic = {
    /**
     * Data
     */
    data: Array<BudgetPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Total Limit Minor
     */
    total_limit_minor?: number;
};

/**
 * CategoriesPublic
 */
export type CategoriesPublic = {
    /**
     * Data
     */
    data: Array<CategoryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
    /**
     * Name
     */
    name: string;
    kind?: CategoryKind;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * CategoryDepth
 *
 * Whether spending is reported per subcategory or rolled up to its parent.
 */
export const CategoryDepth = { LEAF: 'leaf', PARENT: 'parent' } as const;

/**
 * CategoryDepth
 *
 * Whether spending is reported per subcategory or rolled up to its parent.
 */
export type CategoryDepth = typeof CategoryDepth[keyof typeof CategoryDepth];

/**
 * CategoryKind
 */
export const CategoryKind = { EXPENSE: 'expense', INCOME: 'income' } as const;

/**
 * CategoryKind
 */
export type CategoryKind = typeof CategoryKind[keyof typeof CategoryKind];

/**
 * CategoryPublic
 */
export type CategoryPublic = {
    /**
     * Name
     */
    name: string;
    kind?: CategoryKind;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Is System
     */
    is_system?: boolean;
    /**
     * Archived At
     */
    archived_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * CategorySpendSlice
 *
 * One category's share of the spending in a period.
 */
export type CategorySpendSlice = {
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Category Name
     */
    category_name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Parent Name
     */
    parent_name?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Transaction Count
     */
    transaction_count: number;
    /**
     * Share
     */
    share: number;
};

/**
 * CategoryTreeNode
 */
export type CategoryTreeNode = {
    /**
     * Name
     */
    name: string;
    kind?: CategoryKind;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Is System
     */
    is_system?: boolean;
    /**
     * Archived At
     */
    archived_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Children
     */
    children?: Array<CategoryPublic>;
};

/**
 * CategoryTreePublic
 */
export type CategoryTreePublic = {
    /**
     * Data
     */
    data: Array<CategoryTreeNode>;
    /**
     * Count
     */
    count: number;
};

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
    /**
     * Is Archived
     */
    is_archived?: boolean | null;
};

/**
 * EmailVerificationConfirm
 */
export type EmailVerificationConfirm = {
    /**
     * Token
     */
    token: string;
};

/**
 * EmailVerificationRequest
 */
export type EmailVerificationRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HouseholdInviteAccept
 */
export type HouseholdInviteAccept = {
    /**
     * Token
     */
    token: string;
};

/**
 * HouseholdInviteCreate
 */
export type HouseholdInviteCreate = {
    /**
     * Email
     */
    email: string;
    role?: HouseholdRole;
};

/**
 * HouseholdInvitePreview
 *
 * What the join page may show before the recipient has signed in.
 *
 * Deliberately thin: anyone holding the link can read this, so it carries
 * only what is needed to decide whether to accept, and nothing about the
 * household's money.
 */
export type HouseholdInvitePreview = {
    /**
     * Household Name
     */
    household_name: string;
    /**
     * Invited By
     */
    invited_by: string;
    /**
     * Email
     */
    email: string;
    role: HouseholdRole;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * HouseholdInvitePublic
 */
export type HouseholdInvitePublic = {
    /**
     * Email
     */
    email: string;
    role?: HouseholdRole;
    /**
     * Expires At
     */
    expires_at: string;
    status?: HouseholdInviteStatus;
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HouseholdInviteStatus
 */
export const HouseholdInviteStatus = {
    PENDING: 'pending',
    ACCEPTED: 'accepted',
    REVOKED: 'revoked',
    EXPIRED: 'expired'
} as const;

/**
 * HouseholdInviteStatus
 */
export type HouseholdInviteStatus = typeof HouseholdInviteStatus[keyof typeof HouseholdInviteStatus];

/**
 * HouseholdInvitesPublic
 */
export type HouseholdInvitesPublic = {
    /**
     * Data
     */
    data: Array<HouseholdInvitePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HouseholdMemberPublic
 */
export type HouseholdMemberPublic = {
    role?: HouseholdRole;
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HouseholdMemberUpdate
 */
export type HouseholdMemberUpdate = {
    role: HouseholdRole;
};

/**
 * HouseholdMembersPublic
 */
export type HouseholdMembersPublic = {
    /**
     * Data
     */
    data: Array<HouseholdMemberPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HouseholdPublic
 */
export type HouseholdPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Currency Code
     */
    currency_code?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Member Count
     */
    member_count?: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * HouseholdRole
 */
export const HouseholdRole = { OWNER: 'owner', MEMBER: 'member' } as const;

/**
 * HouseholdRole
 */
export type HouseholdRole = typeof HouseholdRole[keyof typeof HouseholdRole];

/**
 * HouseholdUpdate
 */
export type HouseholdUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * IncomeExpenseReport
 */
export type IncomeExpenseReport = {
    period: ReportPeriod;
    /**
     * Months
     */
    months: Array<MonthlyFlow>;
    /**
     * Total Income Minor
     */
    total_income_minor: number;
    /**
     * Total Expense Minor
     */
    total_expense_minor: number;
    /**
     * Total Net Minor
     */
    total_net_minor: number;
    /**
     * Average Savings Rate
     */
    average_savings_rate?: number | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * MonthSummaryReport
 *
 * The dashboard figures for one month, in a single request.
 */
export type MonthSummaryReport = {
    period: ReportPeriod;
    /**
     * Income Minor
     */
    income_minor: number;
    /**
     * Expense Minor
     */
    expense_minor: number;
    /**
     * Net Minor
     */
    net_minor: number;
    /**
     * Net Worth Minor
     */
    net_worth_minor: number;
    /**
     * Budgeted Minor
     */
    budgeted_minor: number;
    /**
     * Over Budget Category Count
     */
    over_budget_category_count: number;
    /**
     * Transaction Count
     */
    transaction_count: number;
    /**
     * Top Categories
     */
    top_categories: Array<CategorySpendSlice>;
};

/**
 * MonthlyFlow
 *
 * Money in and out for one month.
 */
export type MonthlyFlow = {
    /**
     * Month
     */
    month: string;
    /**
     * Income Minor
     */
    income_minor: number;
    /**
     * Expense Minor
     */
    expense_minor: number;
    /**
     * Net Minor
     */
    net_minor: number;
    /**
     * Cumulative Net Minor
     */
    cumulative_net_minor: number;
    /**
     * Savings Rate
     */
    savings_rate?: number | null;
};

/**
 * PasswordResetConfirm
 */
export type PasswordResetConfirm = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * PasswordResetVerify
 */
export type PasswordResetVerify = {
    /**
     * Token
     */
    token: string;
};

/**
 * PasswordUpdate
 */
export type PasswordUpdate = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * RecurrenceFrequency
 */
export const RecurrenceFrequency = {
    WEEKLY: 'weekly',
    MONTHLY: 'monthly',
    YEARLY: 'yearly'
} as const;

/**
 * RecurrenceFrequency
 */
export type RecurrenceFrequency = typeof RecurrenceFrequency[keyof typeof RecurrenceFrequency];

/**
 * RecurringRuleCreate
 */
export type RecurringRuleCreate = {
    /**
     * Name
     */
    name: string;
    frequency?: RecurrenceFrequency;
    /**
     * Interval
     */
    interval?: number;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Day Of Month
     */
    day_of_month?: number | null;
    kind?: TransactionKind;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Merchant
     */
    merchant?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Counter Account Id
     */
    counter_account_id?: string | null;
};

/**
 * RecurringRulePublic
 */
export type RecurringRulePublic = {
    /**
     * Name
     */
    name: string;
    frequency?: RecurrenceFrequency;
    /**
     * Interval
     */
    interval?: number;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Day Of Month
     */
    day_of_month?: number | null;
    kind?: TransactionKind;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Merchant
     */
    merchant?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Counter Account Id
     */
    counter_account_id?: string | null;
    /**
     * Next Occurrence On
     */
    next_occurrence_on?: string | null;
    /**
     * Last Generated On
     */
    last_generated_on?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * RecurringRuleUpdate
 */
export type RecurringRuleUpdate = {
    /**
     * Name
     */
    name?: string | null;
    frequency?: RecurrenceFrequency | null;
    /**
     * Interval
     */
    interval?: number | null;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Day Of Month
     */
    day_of_month?: number | null;
    /**
     * Amount Minor
     */
    amount_minor?: number | null;
    /**
     * Merchant
     */
    merchant?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * RecurringRulesPublic
 */
export type RecurringRulesPublic = {
    /**
     * Data
     */
    data: Array<RecurringRulePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * RecurringRunResult
 *
 * What one materialization pass did.
 */
export type RecurringRunResult = {
    /**
     * Created Count
     */
    created_count: number;
    /**
     * Skipped Count
     */
    skipped_count: number;
    /**
     * Rules Advanced
     */
    rules_advanced: number;
};

/**
 * ReportPeriod
 *
 * The period a report covers, resolved to real dates.
 */
export type ReportPeriod = {
    /**
     * Date From
     */
    date_from: string;
    /**
     * Date To
     */
    date_to: string;
    /**
     * Currency Code
     */
    currency_code: string;
};

/**
 * SpendByCategoryReport
 */
export type SpendByCategoryReport = {
    period: ReportPeriod;
    kind: TransactionKind;
    depth: CategoryDepth;
    /**
     * Total Minor
     */
    total_minor: number;
    /**
     * Slices
     */
    slices: Array<CategorySpendSlice>;
};

/**
 * SpendOverTimeReport
 */
export type SpendOverTimeReport = {
    period: ReportPeriod;
    granularity: TimeGranularity;
    kind: TransactionKind;
    /**
     * Total Minor
     */
    total_minor: number;
    /**
     * Average Minor
     */
    average_minor: number;
    /**
     * Points
     */
    points: Array<TimeSeriesPoint>;
};

/**
 * TimeGranularity
 */
export const TimeGranularity = { DAY: 'day', MONTH: 'month' } as const;

/**
 * TimeGranularity
 */
export type TimeGranularity = typeof TimeGranularity[keyof typeof TimeGranularity];

/**
 * TimeSeriesPoint
 *
 * One bucket of a time series.
 */
export type TimeSeriesPoint = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Transaction Count
     */
    transaction_count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TransactionCreate
 */
export type TransactionCreate = {
    kind: TransactionKind;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Occurred On
     */
    occurred_on: string;
    /**
     * Merchant
     */
    merchant?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Counter Account Id
     */
    counter_account_id?: string | null;
};

/**
 * TransactionKind
 */
export const TransactionKind = {
    EXPENSE: 'expense',
    INCOME: 'income',
    TRANSFER: 'transfer'
} as const;

/**
 * TransactionKind
 */
export type TransactionKind = typeof TransactionKind[keyof typeof TransactionKind];

/**
 * TransactionPublic
 */
export type TransactionPublic = {
    kind: TransactionKind;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Occurred On
     */
    occurred_on: string;
    /**
     * Merchant
     */
    merchant?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Counter Account Id
     */
    counter_account_id?: string | null;
    /**
     * Recurring Rule Id
     */
    recurring_rule_id?: string | null;
    /**
     * Is Generated
     */
    is_generated?: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * TransactionSort
 */
export const TransactionSort = {
    '-DATE': '-date',
    DATE: 'date',
    '-AMOUNT': '-amount',
    AMOUNT: 'amount'
} as const;

/**
 * TransactionSort
 */
export type TransactionSort = typeof TransactionSort[keyof typeof TransactionSort];

/**
 * TransactionUpdate
 */
export type TransactionUpdate = {
    kind?: TransactionKind | null;
    /**
     * Amount Minor
     */
    amount_minor?: number | null;
    /**
     * Occurred On
     */
    occurred_on?: string | null;
    /**
     * Merchant
     */
    merchant?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Account Id
     */
    account_id?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Counter Account Id
     */
    counter_account_id?: string | null;
};

/**
 * TransactionsPublic
 */
export type TransactionsPublic = {
    /**
     * Data
     */
    data: Array<TransactionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UpcomingOccurrence
 *
 * A date a rule will fall due on, not yet recorded.
 */
export type UpcomingOccurrence = {
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Name
     */
    name: string;
    kind: TransactionKind;
    /**
     * Amount Minor
     */
    amount_minor: number;
    /**
     * Occurs On
     */
    occurs_on: string;
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Category Id
     */
    category_id?: string | null;
};

/**
 * UpcomingOccurrencesPublic
 */
export type UpcomingOccurrencesPublic = {
    /**
     * Data
     */
    data: Array<UpcomingOccurrence>;
    /**
     * Count
     */
    count: number;
    /**
     * Total Minor
     */
    total_minor?: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Invite Token
     */
    invite_token?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type UsersGetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersGetUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersGetUsersError = UsersGetUsersErrors[keyof UsersGetUsersErrors];

export type UsersGetUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersGetUsersResponse = UsersGetUsersResponses[keyof UsersGetUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersGetUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersGetUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersGetUserMeResponse = UsersGetUserMeResponses[keyof UsersGetUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersGetUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersGetUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersGetUserByIdError = UsersGetUserByIdErrors[keyof UsersGetUserByIdErrors];

export type UsersGetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersGetUserByIdResponse = UsersGetUserByIdResponses[keyof UsersGetUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UsersUpdatePasswordMeData = {
    body: PasswordUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type HouseholdsGetHouseholdMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/households/me';
};

export type HouseholdsGetHouseholdMeResponses = {
    /**
     * Successful Response
     */
    200: HouseholdPublic;
};

export type HouseholdsGetHouseholdMeResponse = HouseholdsGetHouseholdMeResponses[keyof HouseholdsGetHouseholdMeResponses];

export type HouseholdsUpdateHouseholdMeData = {
    body: HouseholdUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/households/me';
};

export type HouseholdsUpdateHouseholdMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsUpdateHouseholdMeError = HouseholdsUpdateHouseholdMeErrors[keyof HouseholdsUpdateHouseholdMeErrors];

export type HouseholdsUpdateHouseholdMeResponses = {
    /**
     * Successful Response
     */
    200: HouseholdPublic;
};

export type HouseholdsUpdateHouseholdMeResponse = HouseholdsUpdateHouseholdMeResponses[keyof HouseholdsUpdateHouseholdMeResponses];

export type HouseholdsListHouseholdMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/households/me/members';
};

export type HouseholdsListHouseholdMembersResponses = {
    /**
     * Successful Response
     */
    200: HouseholdMembersPublic;
};

export type HouseholdsListHouseholdMembersResponse = HouseholdsListHouseholdMembersResponses[keyof HouseholdsListHouseholdMembersResponses];

export type HouseholdsLeaveHouseholdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/households/me/members/me';
};

export type HouseholdsLeaveHouseholdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type HouseholdsLeaveHouseholdResponse = HouseholdsLeaveHouseholdResponses[keyof HouseholdsLeaveHouseholdResponses];

export type HouseholdsRemoveHouseholdMemberData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/households/me/members/{user_id}';
};

export type HouseholdsRemoveHouseholdMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsRemoveHouseholdMemberError = HouseholdsRemoveHouseholdMemberErrors[keyof HouseholdsRemoveHouseholdMemberErrors];

export type HouseholdsRemoveHouseholdMemberResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type HouseholdsRemoveHouseholdMemberResponse = HouseholdsRemoveHouseholdMemberResponses[keyof HouseholdsRemoveHouseholdMemberResponses];

export type HouseholdsUpdateHouseholdMemberData = {
    body: HouseholdMemberUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/households/me/members/{user_id}';
};

export type HouseholdsUpdateHouseholdMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsUpdateHouseholdMemberError = HouseholdsUpdateHouseholdMemberErrors[keyof HouseholdsUpdateHouseholdMemberErrors];

export type HouseholdsUpdateHouseholdMemberResponses = {
    /**
     * Successful Response
     */
    200: HouseholdMemberPublic;
};

export type HouseholdsUpdateHouseholdMemberResponse = HouseholdsUpdateHouseholdMemberResponses[keyof HouseholdsUpdateHouseholdMemberResponses];

export type HouseholdsListHouseholdInvitesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: HouseholdInviteStatus | null;
    };
    url: '/api/v1/households/me/invites';
};

export type HouseholdsListHouseholdInvitesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsListHouseholdInvitesError = HouseholdsListHouseholdInvitesErrors[keyof HouseholdsListHouseholdInvitesErrors];

export type HouseholdsListHouseholdInvitesResponses = {
    /**
     * Successful Response
     */
    200: HouseholdInvitesPublic;
};

export type HouseholdsListHouseholdInvitesResponse = HouseholdsListHouseholdInvitesResponses[keyof HouseholdsListHouseholdInvitesResponses];

export type HouseholdsCreateHouseholdInviteData = {
    body: HouseholdInviteCreate;
    path?: never;
    query?: never;
    url: '/api/v1/households/me/invites';
};

export type HouseholdsCreateHouseholdInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsCreateHouseholdInviteError = HouseholdsCreateHouseholdInviteErrors[keyof HouseholdsCreateHouseholdInviteErrors];

export type HouseholdsCreateHouseholdInviteResponses = {
    /**
     * Successful Response
     */
    200: HouseholdInvitePublic;
};

export type HouseholdsCreateHouseholdInviteResponse = HouseholdsCreateHouseholdInviteResponses[keyof HouseholdsCreateHouseholdInviteResponses];

export type HouseholdsRevokeHouseholdInviteData = {
    body?: never;
    path: {
        /**
         * Invite Id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/v1/households/me/invites/{invite_id}';
};

export type HouseholdsRevokeHouseholdInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsRevokeHouseholdInviteError = HouseholdsRevokeHouseholdInviteErrors[keyof HouseholdsRevokeHouseholdInviteErrors];

export type HouseholdsRevokeHouseholdInviteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type HouseholdsRevokeHouseholdInviteResponse = HouseholdsRevokeHouseholdInviteResponses[keyof HouseholdsRevokeHouseholdInviteResponses];

export type HouseholdsAcceptHouseholdInviteData = {
    body: HouseholdInviteAccept;
    path?: never;
    query?: never;
    url: '/api/v1/households/invites/accept';
};

export type HouseholdsAcceptHouseholdInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsAcceptHouseholdInviteError = HouseholdsAcceptHouseholdInviteErrors[keyof HouseholdsAcceptHouseholdInviteErrors];

export type HouseholdsAcceptHouseholdInviteResponses = {
    /**
     * Successful Response
     */
    200: HouseholdPublic;
};

export type HouseholdsAcceptHouseholdInviteResponse = HouseholdsAcceptHouseholdInviteResponses[keyof HouseholdsAcceptHouseholdInviteResponses];

export type HouseholdsPreviewHouseholdInviteData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/households/invites/{token}';
};

export type HouseholdsPreviewHouseholdInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsPreviewHouseholdInviteError = HouseholdsPreviewHouseholdInviteErrors[keyof HouseholdsPreviewHouseholdInviteErrors];

export type HouseholdsPreviewHouseholdInviteResponses = {
    /**
     * Successful Response
     */
    200: HouseholdInvitePreview;
};

export type HouseholdsPreviewHouseholdInviteResponse = HouseholdsPreviewHouseholdInviteResponses[keyof HouseholdsPreviewHouseholdInviteResponses];

export type CategoriesListCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Archived
         */
        include_archived?: boolean;
        /**
         * Kind
         */
        kind?: CategoryKind | null;
        /**
         * Parent Id
         */
        parent_id?: string | null;
    };
    url: '/api/v1/categories/';
};

export type CategoriesListCategoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesListCategoriesError = CategoriesListCategoriesErrors[keyof CategoriesListCategoriesErrors];

export type CategoriesListCategoriesResponses = {
    /**
     * Successful Response
     */
    200: CategoriesPublic;
};

export type CategoriesListCategoriesResponse = CategoriesListCategoriesResponses[keyof CategoriesListCategoriesResponses];

export type CategoriesCreateCategoryData = {
    body: CategoryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type CategoriesCreateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesCreateCategoryError = CategoriesCreateCategoryErrors[keyof CategoriesCreateCategoryErrors];

export type CategoriesCreateCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesCreateCategoryResponse = CategoriesCreateCategoryResponses[keyof CategoriesCreateCategoryResponses];

export type CategoriesGetCategoryTreeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Archived
         */
        include_archived?: boolean;
        /**
         * Kind
         */
        kind?: CategoryKind | null;
    };
    url: '/api/v1/categories/tree';
};

export type CategoriesGetCategoryTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesGetCategoryTreeError = CategoriesGetCategoryTreeErrors[keyof CategoriesGetCategoryTreeErrors];

export type CategoriesGetCategoryTreeResponses = {
    /**
     * Successful Response
     */
    200: CategoryTreePublic;
};

export type CategoriesGetCategoryTreeResponse = CategoriesGetCategoryTreeResponses[keyof CategoriesGetCategoryTreeResponses];

export type CategoriesDeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type CategoriesDeleteCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesDeleteCategoryError = CategoriesDeleteCategoryErrors[keyof CategoriesDeleteCategoryErrors];

export type CategoriesDeleteCategoryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CategoriesDeleteCategoryResponse = CategoriesDeleteCategoryResponses[keyof CategoriesDeleteCategoryResponses];

export type CategoriesGetCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type CategoriesGetCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesGetCategoryError = CategoriesGetCategoryErrors[keyof CategoriesGetCategoryErrors];

export type CategoriesGetCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesGetCategoryResponse = CategoriesGetCategoryResponses[keyof CategoriesGetCategoryResponses];

export type CategoriesUpdateCategoryData = {
    body: CategoryUpdate;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type CategoriesUpdateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesUpdateCategoryError = CategoriesUpdateCategoryErrors[keyof CategoriesUpdateCategoryErrors];

export type CategoriesUpdateCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesUpdateCategoryResponse = CategoriesUpdateCategoryResponses[keyof CategoriesUpdateCategoryResponses];

export type AccountsListAccountsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Archived
         */
        include_archived?: boolean;
        /**
         * Type
         */
        type?: AccountType | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/accounts/';
};

export type AccountsListAccountsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsListAccountsError = AccountsListAccountsErrors[keyof AccountsListAccountsErrors];

export type AccountsListAccountsResponses = {
    /**
     * Successful Response
     */
    200: AccountsPublic;
};

export type AccountsListAccountsResponse = AccountsListAccountsResponses[keyof AccountsListAccountsResponses];

export type AccountsCreateAccountData = {
    body: AccountCreate;
    path?: never;
    query?: never;
    url: '/api/v1/accounts/';
};

export type AccountsCreateAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsCreateAccountError = AccountsCreateAccountErrors[keyof AccountsCreateAccountErrors];

export type AccountsCreateAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountPublic;
};

export type AccountsCreateAccountResponse = AccountsCreateAccountResponses[keyof AccountsCreateAccountResponses];

export type AccountsDeleteAccountData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}';
};

export type AccountsDeleteAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsDeleteAccountError = AccountsDeleteAccountErrors[keyof AccountsDeleteAccountErrors];

export type AccountsDeleteAccountResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AccountsDeleteAccountResponse = AccountsDeleteAccountResponses[keyof AccountsDeleteAccountResponses];

export type AccountsGetAccountData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}';
};

export type AccountsGetAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsGetAccountError = AccountsGetAccountErrors[keyof AccountsGetAccountErrors];

export type AccountsGetAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountPublic;
};

export type AccountsGetAccountResponse = AccountsGetAccountResponses[keyof AccountsGetAccountResponses];

export type AccountsUpdateAccountData = {
    body: AccountUpdate;
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/accounts/{account_id}';
};

export type AccountsUpdateAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccountsUpdateAccountError = AccountsUpdateAccountErrors[keyof AccountsUpdateAccountErrors];

export type AccountsUpdateAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountPublic;
};

export type AccountsUpdateAccountResponse = AccountsUpdateAccountResponses[keyof AccountsUpdateAccountResponses];

export type TransactionsListTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date From
         */
        date_from?: string | null;
        /**
         * Date To
         */
        date_to?: string | null;
        /**
         * Account Id
         */
        account_id?: string | null;
        /**
         * Category Id
         */
        category_id?: string | null;
        /**
         * Include Subcategories
         */
        include_subcategories?: boolean;
        /**
         * Kind
         */
        kind?: TransactionKind | null;
        /**
         * Min Amount Minor
         */
        min_amount_minor?: number | null;
        /**
         * Max Amount Minor
         */
        max_amount_minor?: number | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        sort?: TransactionSort;
    };
    url: '/api/v1/transactions/';
};

export type TransactionsListTransactionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsListTransactionsError = TransactionsListTransactionsErrors[keyof TransactionsListTransactionsErrors];

export type TransactionsListTransactionsResponses = {
    /**
     * Successful Response
     */
    200: TransactionsPublic;
};

export type TransactionsListTransactionsResponse = TransactionsListTransactionsResponses[keyof TransactionsListTransactionsResponses];

export type TransactionsCreateTransactionData = {
    body: TransactionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/transactions/';
};

export type TransactionsCreateTransactionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsCreateTransactionError = TransactionsCreateTransactionErrors[keyof TransactionsCreateTransactionErrors];

export type TransactionsCreateTransactionResponses = {
    /**
     * Successful Response
     */
    200: TransactionPublic;
};

export type TransactionsCreateTransactionResponse = TransactionsCreateTransactionResponses[keyof TransactionsCreateTransactionResponses];

export type TransactionsDeleteTransactionData = {
    body?: never;
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/api/v1/transactions/{transaction_id}';
};

export type TransactionsDeleteTransactionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsDeleteTransactionError = TransactionsDeleteTransactionErrors[keyof TransactionsDeleteTransactionErrors];

export type TransactionsDeleteTransactionResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type TransactionsDeleteTransactionResponse = TransactionsDeleteTransactionResponses[keyof TransactionsDeleteTransactionResponses];

export type TransactionsGetTransactionData = {
    body?: never;
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/api/v1/transactions/{transaction_id}';
};

export type TransactionsGetTransactionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsGetTransactionError = TransactionsGetTransactionErrors[keyof TransactionsGetTransactionErrors];

export type TransactionsGetTransactionResponses = {
    /**
     * Successful Response
     */
    200: TransactionPublic;
};

export type TransactionsGetTransactionResponse = TransactionsGetTransactionResponses[keyof TransactionsGetTransactionResponses];

export type TransactionsUpdateTransactionData = {
    body: TransactionUpdate;
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/api/v1/transactions/{transaction_id}';
};

export type TransactionsUpdateTransactionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsUpdateTransactionError = TransactionsUpdateTransactionErrors[keyof TransactionsUpdateTransactionErrors];

export type TransactionsUpdateTransactionResponses = {
    /**
     * Successful Response
     */
    200: TransactionPublic;
};

export type TransactionsUpdateTransactionResponse = TransactionsUpdateTransactionResponses[keyof TransactionsUpdateTransactionResponses];

export type BudgetsListBudgetsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Month
         */
        month: string;
    };
    url: '/api/v1/budgets/';
};

export type BudgetsListBudgetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BudgetsListBudgetsError = BudgetsListBudgetsErrors[keyof BudgetsListBudgetsErrors];

export type BudgetsListBudgetsResponses = {
    /**
     * Successful Response
     */
    200: BudgetsPublic;
};

export type BudgetsListBudgetsResponse = BudgetsListBudgetsResponses[keyof BudgetsListBudgetsResponses];

export type BudgetsCreateBudgetData = {
    body: BudgetCreate;
    path?: never;
    query?: never;
    url: '/api/v1/budgets/';
};

export type BudgetsCreateBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BudgetsCreateBudgetError = BudgetsCreateBudgetErrors[keyof BudgetsCreateBudgetErrors];

export type BudgetsCreateBudgetResponses = {
    /**
     * Successful Response
     */
    200: BudgetPublic;
};

export type BudgetsCreateBudgetResponse = BudgetsCreateBudgetResponses[keyof BudgetsCreateBudgetResponses];

export type BudgetsBulkUpsertBudgetsData = {
    body: BudgetBulkUpsert;
    path?: never;
    query?: never;
    url: '/api/v1/budgets/bulk';
};

export type BudgetsBulkUpsertBudgetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BudgetsBulkUpsertBudgetsError = BudgetsBulkUpsertBudgetsErrors[keyof BudgetsBulkUpsertBudgetsErrors];

export type BudgetsBulkUpsertBudgetsResponses = {
    /**
     * Successful Response
     */
    200: BudgetsPublic;
};

export type BudgetsBulkUpsertBudgetsResponse = BudgetsBulkUpsertBudgetsResponses[keyof BudgetsBulkUpsertBudgetsResponses];

export type BudgetsCopyBudgetsData = {
    body: BudgetCopyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/budgets/copy';
};

export type BudgetsCopyBudgetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BudgetsCopyBudgetsError = BudgetsCopyBudgetsErrors[keyof BudgetsCopyBudgetsErrors];

export type BudgetsCopyBudgetsResponses = {
    /**
     * Successful Response
     */
    200: BudgetsPublic;
};

export type BudgetsCopyBudgetsResponse = BudgetsCopyBudgetsResponses[keyof BudgetsCopyBudgetsResponses];

export type BudgetsDeleteBudgetData = {
    body?: never;
    path: {
        /**
         * Budget Id
         */
        budget_id: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget_id}';
};

export type BudgetsDeleteBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BudgetsDeleteBudgetError = BudgetsDeleteBudgetErrors[keyof BudgetsDeleteBudgetErrors];

export type BudgetsDeleteBudgetResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type BudgetsDeleteBudgetResponse = BudgetsDeleteBudgetResponses[keyof BudgetsDeleteBudgetResponses];

export type BudgetsGetBudgetData = {
    body?: never;
    path: {
        /**
         * Budget Id
         */
        budget_id: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget_id}';
};

export type BudgetsGetBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BudgetsGetBudgetError = BudgetsGetBudgetErrors[keyof BudgetsGetBudgetErrors];

export type BudgetsGetBudgetResponses = {
    /**
     * Successful Response
     */
    200: BudgetPublic;
};

export type BudgetsGetBudgetResponse = BudgetsGetBudgetResponses[keyof BudgetsGetBudgetResponses];

export type BudgetsUpdateBudgetData = {
    body: BudgetUpdate;
    path: {
        /**
         * Budget Id
         */
        budget_id: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget_id}';
};

export type BudgetsUpdateBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BudgetsUpdateBudgetError = BudgetsUpdateBudgetErrors[keyof BudgetsUpdateBudgetErrors];

export type BudgetsUpdateBudgetResponses = {
    /**
     * Successful Response
     */
    200: BudgetPublic;
};

export type BudgetsUpdateBudgetResponse = BudgetsUpdateBudgetResponses[keyof BudgetsUpdateBudgetResponses];

export type RecurringRulesListRecurringRulesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Is Active
         */
        is_active?: boolean | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/recurring-rules/';
};

export type RecurringRulesListRecurringRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecurringRulesListRecurringRulesError = RecurringRulesListRecurringRulesErrors[keyof RecurringRulesListRecurringRulesErrors];

export type RecurringRulesListRecurringRulesResponses = {
    /**
     * Successful Response
     */
    200: RecurringRulesPublic;
};

export type RecurringRulesListRecurringRulesResponse = RecurringRulesListRecurringRulesResponses[keyof RecurringRulesListRecurringRulesResponses];

export type RecurringRulesCreateRecurringRuleData = {
    body: RecurringRuleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/recurring-rules/';
};

export type RecurringRulesCreateRecurringRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecurringRulesCreateRecurringRuleError = RecurringRulesCreateRecurringRuleErrors[keyof RecurringRulesCreateRecurringRuleErrors];

export type RecurringRulesCreateRecurringRuleResponses = {
    /**
     * Successful Response
     */
    200: RecurringRulePublic;
};

export type RecurringRulesCreateRecurringRuleResponse = RecurringRulesCreateRecurringRuleResponses[keyof RecurringRulesCreateRecurringRuleResponses];

export type RecurringRulesListUpcomingOccurrencesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Until
         */
        until?: string | null;
    };
    url: '/api/v1/recurring-rules/upcoming';
};

export type RecurringRulesListUpcomingOccurrencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecurringRulesListUpcomingOccurrencesError = RecurringRulesListUpcomingOccurrencesErrors[keyof RecurringRulesListUpcomingOccurrencesErrors];

export type RecurringRulesListUpcomingOccurrencesResponses = {
    /**
     * Successful Response
     */
    200: UpcomingOccurrencesPublic;
};

export type RecurringRulesListUpcomingOccurrencesResponse = RecurringRulesListUpcomingOccurrencesResponses[keyof RecurringRulesListUpcomingOccurrencesResponses];

export type RecurringRulesRunRecurringRulesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Until
         */
        until?: string | null;
    };
    url: '/api/v1/recurring-rules/run';
};

export type RecurringRulesRunRecurringRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecurringRulesRunRecurringRulesError = RecurringRulesRunRecurringRulesErrors[keyof RecurringRulesRunRecurringRulesErrors];

export type RecurringRulesRunRecurringRulesResponses = {
    /**
     * Successful Response
     */
    200: RecurringRunResult;
};

export type RecurringRulesRunRecurringRulesResponse = RecurringRulesRunRecurringRulesResponses[keyof RecurringRulesRunRecurringRulesResponses];

export type RecurringRulesDeleteRecurringRuleData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/recurring-rules/{rule_id}';
};

export type RecurringRulesDeleteRecurringRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecurringRulesDeleteRecurringRuleError = RecurringRulesDeleteRecurringRuleErrors[keyof RecurringRulesDeleteRecurringRuleErrors];

export type RecurringRulesDeleteRecurringRuleResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecurringRulesDeleteRecurringRuleResponse = RecurringRulesDeleteRecurringRuleResponses[keyof RecurringRulesDeleteRecurringRuleResponses];

export type RecurringRulesGetRecurringRuleData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/recurring-rules/{rule_id}';
};

export type RecurringRulesGetRecurringRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecurringRulesGetRecurringRuleError = RecurringRulesGetRecurringRuleErrors[keyof RecurringRulesGetRecurringRuleErrors];

export type RecurringRulesGetRecurringRuleResponses = {
    /**
     * Successful Response
     */
    200: RecurringRulePublic;
};

export type RecurringRulesGetRecurringRuleResponse = RecurringRulesGetRecurringRuleResponses[keyof RecurringRulesGetRecurringRuleResponses];

export type RecurringRulesUpdateRecurringRuleData = {
    body: RecurringRuleUpdate;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/recurring-rules/{rule_id}';
};

export type RecurringRulesUpdateRecurringRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecurringRulesUpdateRecurringRuleError = RecurringRulesUpdateRecurringRuleErrors[keyof RecurringRulesUpdateRecurringRuleErrors];

export type RecurringRulesUpdateRecurringRuleResponses = {
    /**
     * Successful Response
     */
    200: RecurringRulePublic;
};

export type RecurringRulesUpdateRecurringRuleResponse = RecurringRulesUpdateRecurringRuleResponses[keyof RecurringRulesUpdateRecurringRuleResponses];

export type ReportsSpendByCategoryData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Month
         */
        month: string;
        kind?: TransactionKind;
        depth?: CategoryDepth;
    };
    url: '/api/v1/reports/spend-by-category';
};

export type ReportsSpendByCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportsSpendByCategoryError = ReportsSpendByCategoryErrors[keyof ReportsSpendByCategoryErrors];

export type ReportsSpendByCategoryResponses = {
    /**
     * Successful Response
     */
    200: SpendByCategoryReport;
};

export type ReportsSpendByCategoryResponse = ReportsSpendByCategoryResponses[keyof ReportsSpendByCategoryResponses];

export type ReportsSpendOverTimeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Date From
         */
        date_from: string;
        /**
         * Date To
         */
        date_to: string;
        granularity?: TimeGranularity;
        kind?: TransactionKind;
        /**
         * Account Id
         */
        account_id?: string | null;
        /**
         * Category Id
         */
        category_id?: string | null;
    };
    url: '/api/v1/reports/spend-over-time';
};

export type ReportsSpendOverTimeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportsSpendOverTimeError = ReportsSpendOverTimeErrors[keyof ReportsSpendOverTimeErrors];

export type ReportsSpendOverTimeResponses = {
    /**
     * Successful Response
     */
    200: SpendOverTimeReport;
};

export type ReportsSpendOverTimeResponse = ReportsSpendOverTimeResponses[keyof ReportsSpendOverTimeResponses];

export type ReportsIncomeExpenseData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Month From
         */
        month_from: string;
        /**
         * Month To
         */
        month_to: string;
    };
    url: '/api/v1/reports/income-expense';
};

export type ReportsIncomeExpenseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportsIncomeExpenseError = ReportsIncomeExpenseErrors[keyof ReportsIncomeExpenseErrors];

export type ReportsIncomeExpenseResponses = {
    /**
     * Successful Response
     */
    200: IncomeExpenseReport;
};

export type ReportsIncomeExpenseResponse = ReportsIncomeExpenseResponses[keyof ReportsIncomeExpenseResponses];

export type ReportsBudgetProgressData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Month
         */
        month: string;
    };
    url: '/api/v1/reports/budget-progress';
};

export type ReportsBudgetProgressErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportsBudgetProgressError = ReportsBudgetProgressErrors[keyof ReportsBudgetProgressErrors];

export type ReportsBudgetProgressResponses = {
    /**
     * Successful Response
     */
    200: BudgetProgressReport;
};

export type ReportsBudgetProgressResponse = ReportsBudgetProgressResponses[keyof ReportsBudgetProgressResponses];

export type ReportsMonthSummaryData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Month
         */
        month: string;
    };
    url: '/api/v1/reports/summary';
};

export type ReportsMonthSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportsMonthSummaryError = ReportsMonthSummaryErrors[keyof ReportsMonthSummaryErrors];

export type ReportsMonthSummaryResponses = {
    /**
     * Successful Response
     */
    200: MonthSummaryReport;
};

export type ReportsMonthSummaryResponse = ReportsMonthSummaryResponses[keyof ReportsMonthSummaryResponses];

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type PasswordResetRequestPasswordResetData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/request';
};

export type PasswordResetRequestPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PasswordResetRequestPasswordResetError = PasswordResetRequestPasswordResetErrors[keyof PasswordResetRequestPasswordResetErrors];

export type PasswordResetRequestPasswordResetResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PasswordResetRequestPasswordResetResponse = PasswordResetRequestPasswordResetResponses[keyof PasswordResetRequestPasswordResetResponses];

export type PasswordResetVerifyPasswordResetTokenData = {
    body: PasswordResetVerify;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/verify';
};

export type PasswordResetVerifyPasswordResetTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PasswordResetVerifyPasswordResetTokenError = PasswordResetVerifyPasswordResetTokenErrors[keyof PasswordResetVerifyPasswordResetTokenErrors];

export type PasswordResetVerifyPasswordResetTokenResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PasswordResetVerifyPasswordResetTokenResponse = PasswordResetVerifyPasswordResetTokenResponses[keyof PasswordResetVerifyPasswordResetTokenResponses];

export type PasswordResetConfirmPasswordResetData = {
    body: PasswordResetConfirm;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/confirm';
};

export type PasswordResetConfirmPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PasswordResetConfirmPasswordResetError = PasswordResetConfirmPasswordResetErrors[keyof PasswordResetConfirmPasswordResetErrors];

export type PasswordResetConfirmPasswordResetResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PasswordResetConfirmPasswordResetResponse = PasswordResetConfirmPasswordResetResponses[keyof PasswordResetConfirmPasswordResetResponses];

export type EmailVerificationResendVerificationEmailData = {
    body: EmailVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/email-verification/send';
};

export type EmailVerificationResendVerificationEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EmailVerificationResendVerificationEmailError = EmailVerificationResendVerificationEmailErrors[keyof EmailVerificationResendVerificationEmailErrors];

export type EmailVerificationResendVerificationEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type EmailVerificationResendVerificationEmailResponse = EmailVerificationResendVerificationEmailResponses[keyof EmailVerificationResendVerificationEmailResponses];

export type EmailVerificationVerifyEmailData = {
    body: EmailVerificationConfirm;
    path?: never;
    query?: never;
    url: '/api/v1/email-verification/verify';
};

export type EmailVerificationVerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EmailVerificationVerifyEmailError = EmailVerificationVerifyEmailErrors[keyof EmailVerificationVerifyEmailErrors];

export type EmailVerificationVerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type EmailVerificationVerifyEmailResponse = EmailVerificationVerifyEmailResponses[keyof EmailVerificationVerifyEmailResponses];
